# fly.toml app configuration file generated for com-ms-inadvance on 2024-03-26T09:07:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'com-ms-inadvance'
primary_region = 'mia'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[env]
  HOSTNAME = '0.0.0.0'
  SPRING_DATASOURCE_PASSWORD = 'dK3lxjdSnbRQw80'
  SPRING_DATASOURCE_URL = 'jdbc:postgresql://inadvancedb.internal:5432/inadvance'
  SPRING_DATASOURCE_USERNAME = 'postgres'

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 9000
  processes = ['app']

[[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
