package com.ms.inadvance.entity;
// Generated 19-03-2024 15:48:26 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BrokerCompany generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "broker_company")
public class BrokerCompany implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String name;
	private String phone;
	private String physicalAdd;
	private String webSite;
	private Set<Realtor> realtors = new HashSet<Realtor>(0);

	public BrokerCompany() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone", nullable = false, length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "physical_add", nullable = false, length = 50)
	public String getPhysicalAdd() {
		return this.physicalAdd;
	}

	public void setPhysicalAdd(String physicalAdd) {
		this.physicalAdd = physicalAdd;
	}

	@Column(name = "web_site", length = 500)
	public String getWebSite() {
		return this.webSite;
	}

	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brokerCompany")
	public Set<Realtor> getRealtors() {
		return this.realtors;
	}

	public void setRealtors(Set<Realtor> realtors) {
		this.realtors = realtors;
	}

}
