package com.ms.inadvance.entity;
// Generated 19-03-2024 15:48:26 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@PrimaryKeyJoinColumn(name="id")
@Table(schema = "public", name = "client")
public class Client extends Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Users users;
	private String updateUser;
	private Date updateDate;
	private Set<ClientOperation> clientOperations = new HashSet<ClientOperation>(0);
	private Set<LoanClient> loanClients = new HashSet<LoanClient>(0);

	public Client() {
	}
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "update_user", nullable = false, length = 50)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<ClientOperation> getClientOperations() {
		return this.clientOperations;
	}

	public void setClientOperations(Set<ClientOperation> clientOperations) {
		this.clientOperations = clientOperations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<LoanClient> getLoanClients() {
		return this.loanClients;
	}

	public void setLoanClients(Set<LoanClient> loanClients) {
		this.loanClients = loanClients;
	}

}
