package com.ms.inadvance.entity;
// Generated 19-03-2024 15:48:26 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LetterFixdata generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "letter_fixdata")
public class LetterFixData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String conditions;
	private boolean deleted;
	private String finaltext;
	private String subject;
	private Set<LetterConfig> letterConfigs = new HashSet<LetterConfig>(0);

	public LetterFixData() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "conditions", nullable = false, length = 500)
	public String getConditions() {
		return this.conditions;
	}

	public void setConditions(String conditions) {
		this.conditions = conditions;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	@Column(name = "finaltext", nullable = false, length = 500)
	public String getFinaltext() {
		return this.finaltext;
	}

	public void setFinaltext(String finaltext) {
		this.finaltext = finaltext;
	}

	@Column(name = "subject", nullable = false, length = 500)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "letterFixdata")
	public Set<LetterConfig> getLetterConfigs() {
		return this.letterConfigs;
	}

	public void setLetterConfigs(Set<LetterConfig> letterConfigs) {
		this.letterConfigs = letterConfigs;
	}

}
