package com.ms.inadvance.entity;
// Generated 19-03-2024 15:48:26 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RealtorOperation generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "realtor_operation")
public class RealtorOperation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private Operation operation;
	private Realtor realtor;

	public RealtorOperation() {
	}

	public RealtorOperation(long id, Operation operation, Realtor realtor) {
		this.id = id;
		this.operation = operation;
		this.realtor = realtor;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operation_id", nullable = false)
	public Operation getOperation() {
		return this.operation;
	}

	public void setOperation(Operation operation) {
		this.operation = operation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "realtor_id", nullable = false)
	public Realtor getRealtor() {
		return this.realtor;
	}

	public void setRealtor(Realtor realtor) {
		this.realtor = realtor;
	}

}
