package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asignacion generated by hbm2java
 */
@Entity
@Table(name = "asignacion")
public class Asignacion implements java.io.Serializable {

	private int asgId;
	private Persona persona;
	private Proyecto proyecto;
	private Set timeReports = new HashSet(0);

	public Asignacion() {
	}

	public Asignacion(int asgId, Persona persona, Proyecto proyecto) {
		this.asgId = asgId;
		this.persona = persona;
		this.proyecto = proyecto;
	}

	public Asignacion(int asgId, Persona persona, Proyecto proyecto, Set timeReports) {
		this.asgId = asgId;
		this.persona = persona;
		this.proyecto = proyecto;
		this.timeReports = timeReports;
	}

	@Id

	@Column(name = "asg_id", unique = true, nullable = false)
	public int getAsgId() {
		return this.asgId;
	}

	public void setAsgId(int asgId) {
		this.asgId = asgId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proyecto", nullable = false)
	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asignacion")
	public Set getTimeReports() {
		return this.timeReports;
	}

	public void setTimeReports(Set timeReports) {
		this.timeReports = timeReports;
	}

}
