package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Compania generated by hbm2java
 */
@Entity
@Table(name = "compania")
public class Compania implements java.io.Serializable {

	private int ciaId;
	private Pais pais;
	private String ciaNombre;
	private String ciaRazonSocial;
	private Set proyectos = new HashSet(0);

	public Compania() {
	}

	public Compania(int ciaId, Pais pais) {
		this.ciaId = ciaId;
		this.pais = pais;
	}

	public Compania(int ciaId, Pais pais, String ciaNombre, String ciaRazonSocial, Set proyectos) {
		this.ciaId = ciaId;
		this.pais = pais;
		this.ciaNombre = ciaNombre;
		this.ciaRazonSocial = ciaRazonSocial;
		this.proyectos = proyectos;
	}

	@Id

	@Column(name = "cia_id", unique = true, nullable = false)
	public int getCiaId() {
		return this.ciaId;
	}

	public void setCiaId(int ciaId) {
		this.ciaId = ciaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pais", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@Column(name = "cia_nombre")
	public String getCiaNombre() {
		return this.ciaNombre;
	}

	public void setCiaNombre(String ciaNombre) {
		this.ciaNombre = ciaNombre;
	}

	@Column(name = "cia_razon_social")
	public String getCiaRazonSocial() {
		return this.ciaRazonSocial;
	}

	public void setCiaRazonSocial(String ciaRazonSocial) {
		this.ciaRazonSocial = ciaRazonSocial;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
	public Set getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set proyectos) {
		this.proyectos = proyectos;
	}

}
