package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comuna generated by hbm2java
 */
@Entity
@Table(name = "comuna")
public class Comuna implements java.io.Serializable {

	private int comId;
	private Region region;
	private String comDescripcion;

	public Comuna() {
	}

	public Comuna(int comId, Region region, String comDescripcion) {
		this.comId = comId;
		this.region = region;
		this.comDescripcion = comDescripcion;
	}

	@Id

	@Column(name = "com_id", unique = true, nullable = false)
	public int getComId() {
		return this.comId;
	}

	public void setComId(int comId) {
		this.comId = comId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_region", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "com_descripcion", nullable = false, length = 100)
	public String getComDescripcion() {
		return this.comDescripcion;
	}

	public void setComDescripcion(String comDescripcion) {
		this.comDescripcion = comDescripcion;
	}

}
