package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estructura generated by hbm2java
 */
@Entity
@Table(name = "estructura")
public class Estructura implements java.io.Serializable {

	private int estId;
	private String estNombre;
	private BigDecimal estTasaCosto;
	private Set personaEstructuras = new HashSet(0);

	public Estructura() {
	}

	public Estructura(int estId, String estNombre) {
		this.estId = estId;
		this.estNombre = estNombre;
	}

	public Estructura(int estId, String estNombre, BigDecimal estTasaCosto, Set personaEstructuras) {
		this.estId = estId;
		this.estNombre = estNombre;
		this.estTasaCosto = estTasaCosto;
		this.personaEstructuras = personaEstructuras;
	}

	@Id

	@Column(name = "est_id", unique = true, nullable = false)
	public int getEstId() {
		return this.estId;
	}

	public void setEstId(int estId) {
		this.estId = estId;
	}

	@Column(name = "est_nombre", nullable = false)
	public String getEstNombre() {
		return this.estNombre;
	}

	public void setEstNombre(String estNombre) {
		this.estNombre = estNombre;
	}

	@Column(name = "est_tasa_costo", precision = 10)
	public BigDecimal getEstTasaCosto() {
		return this.estTasaCosto;
	}

	public void setEstTasaCosto(BigDecimal estTasaCosto) {
		this.estTasaCosto = estTasaCosto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estructura")
	public Set getPersonaEstructuras() {
		return this.personaEstructuras;
	}

	public void setPersonaEstructuras(Set personaEstructuras) {
		this.personaEstructuras = personaEstructuras;
	}

}
