package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MetodoPago generated by hbm2java
 */
@Entity
@Table(name = "metodo_pago")
public class MetodoPago implements java.io.Serializable {

	private int mpaId;
	private Persona persona;
	private TipoPago tipoPago;
	private String mpaCuenta;
	private String mpaTipoCuenta;
	private String mpaEmail;
	private String mpaBanco;

	public MetodoPago() {
	}

	public MetodoPago(int mpaId, Persona persona, TipoPago tipoPago) {
		this.mpaId = mpaId;
		this.persona = persona;
		this.tipoPago = tipoPago;
	}

	public MetodoPago(int mpaId, Persona persona, TipoPago tipoPago, String mpaCuenta, String mpaTipoCuenta,
			String mpaEmail, String mpaBanco) {
		this.mpaId = mpaId;
		this.persona = persona;
		this.tipoPago = tipoPago;
		this.mpaCuenta = mpaCuenta;
		this.mpaTipoCuenta = mpaTipoCuenta;
		this.mpaEmail = mpaEmail;
		this.mpaBanco = mpaBanco;
	}

	@Id

	@Column(name = "mpa_id", unique = true, nullable = false)
	public int getMpaId() {
		return this.mpaId;
	}

	public void setMpaId(int mpaId) {
		this.mpaId = mpaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_pago", nullable = false)
	public TipoPago getTipoPago() {
		return this.tipoPago;
	}

	public void setTipoPago(TipoPago tipoPago) {
		this.tipoPago = tipoPago;
	}

	@Column(name = "mpa_cuenta")
	public String getMpaCuenta() {
		return this.mpaCuenta;
	}

	public void setMpaCuenta(String mpaCuenta) {
		this.mpaCuenta = mpaCuenta;
	}

	@Column(name = "mpa_tipo_cuenta")
	public String getMpaTipoCuenta() {
		return this.mpaTipoCuenta;
	}

	public void setMpaTipoCuenta(String mpaTipoCuenta) {
		this.mpaTipoCuenta = mpaTipoCuenta;
	}

	@Column(name = "mpa_email")
	public String getMpaEmail() {
		return this.mpaEmail;
	}

	public void setMpaEmail(String mpaEmail) {
		this.mpaEmail = mpaEmail;
	}

	@Column(name = "mpa_banco")
	public String getMpaBanco() {
		return this.mpaBanco;
	}

	public void setMpaBanco(String mpaBanco) {
		this.mpaBanco = mpaBanco;
	}

}
