package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais")
public class Pais implements java.io.Serializable {

	private int paiId;
	private String paiDescripcion;
	private Set clientes = new HashSet(0);
	private Set personasForIdPaisNacionalidad = new HashSet(0);
	private Set companias = new HashSet(0);
	private Set regions = new HashSet(0);
	private Set personasForIdPaisResidencia = new HashSet(0);

	public Pais() {
	}

	public Pais(int paiId, String paiDescripcion) {
		this.paiId = paiId;
		this.paiDescripcion = paiDescripcion;
	}

	public Pais(int paiId, String paiDescripcion, Set clientes, Set personasForIdPaisNacionalidad, Set companias,
			Set regions, Set personasForIdPaisResidencia) {
		this.paiId = paiId;
		this.paiDescripcion = paiDescripcion;
		this.clientes = clientes;
		this.personasForIdPaisNacionalidad = personasForIdPaisNacionalidad;
		this.companias = companias;
		this.regions = regions;
		this.personasForIdPaisResidencia = personasForIdPaisResidencia;
	}

	@Id

	@Column(name = "pai_id", unique = true, nullable = false)
	public int getPaiId() {
		return this.paiId;
	}

	public void setPaiId(int paiId) {
		this.paiId = paiId;
	}

	@Column(name = "pai_descripcion", nullable = false, length = 100)
	public String getPaiDescripcion() {
		return this.paiDescripcion;
	}

	public void setPaiDescripcion(String paiDescripcion) {
		this.paiDescripcion = paiDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paisByIdPaisNacionalidad")
	public Set getPersonasForIdPaisNacionalidad() {
		return this.personasForIdPaisNacionalidad;
	}

	public void setPersonasForIdPaisNacionalidad(Set personasForIdPaisNacionalidad) {
		this.personasForIdPaisNacionalidad = personasForIdPaisNacionalidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set getCompanias() {
		return this.companias;
	}

	public void setCompanias(Set companias) {
		this.companias = companias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set getRegions() {
		return this.regions;
	}

	public void setRegions(Set regions) {
		this.regions = regions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paisByIdPaisResidencia")
	public Set getPersonasForIdPaisResidencia() {
		return this.personasForIdPaisResidencia;
	}

	public void setPersonasForIdPaisResidencia(Set personasForIdPaisResidencia) {
		this.personasForIdPaisResidencia = personasForIdPaisResidencia;
	}

}
