package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonaEstructura generated by hbm2java
 */
@Entity
@Table(name = "persona_estructura")
public class PersonaEstructura implements java.io.Serializable {

	private int peeId;
	private Estructura estructura;
	private Persona persona;
	private Date peeFechaInicio;
	private Date peeFechaFin;
	private String peeEstado;

	public PersonaEstructura() {
	}

	public PersonaEstructura(int peeId, Persona persona) {
		this.peeId = peeId;
		this.persona = persona;
	}

	public PersonaEstructura(int peeId, Estructura estructura, Persona persona, Date peeFechaInicio, Date peeFechaFin,
			String peeEstado) {
		this.peeId = peeId;
		this.estructura = estructura;
		this.persona = persona;
		this.peeFechaInicio = peeFechaInicio;
		this.peeFechaFin = peeFechaFin;
		this.peeEstado = peeEstado;
	}

	@Id

	@Column(name = "pee_id", unique = true, nullable = false)
	public int getPeeId() {
		return this.peeId;
	}

	public void setPeeId(int peeId) {
		this.peeId = peeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estructura")
	public Estructura getEstructura() {
		return this.estructura;
	}

	public void setEstructura(Estructura estructura) {
		this.estructura = estructura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pee_fecha_inicio", length = 29)
	public Date getPeeFechaInicio() {
		return this.peeFechaInicio;
	}

	public void setPeeFechaInicio(Date peeFechaInicio) {
		this.peeFechaInicio = peeFechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pee_fecha_fin", length = 29)
	public Date getPeeFechaFin() {
		return this.peeFechaFin;
	}

	public void setPeeFechaFin(Date peeFechaFin) {
		this.peeFechaFin = peeFechaFin;
	}

	@Column(name = "pee_estado")
	public String getPeeEstado() {
		return this.peeEstado;
	}

	public void setPeeEstado(String peeEstado) {
		this.peeEstado = peeEstado;
	}

}
