package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pricing generated by hbm2java
 */
@Entity
@Table(name = "pricing")
public class Pricing implements java.io.Serializable {

	private int priId;
	private BigDecimal priTargetMarging;
	private BigDecimal priRevenue;
	private Set proyectos = new HashSet(0);

	public Pricing() {
	}

	public Pricing(int priId) {
		this.priId = priId;
	}

	public Pricing(int priId, BigDecimal priTargetMarging, BigDecimal priRevenue, Set proyectos) {
		this.priId = priId;
		this.priTargetMarging = priTargetMarging;
		this.priRevenue = priRevenue;
		this.proyectos = proyectos;
	}

	@Id

	@Column(name = "pri_id", unique = true, nullable = false)
	public int getPriId() {
		return this.priId;
	}

	public void setPriId(int priId) {
		this.priId = priId;
	}

	@Column(name = "pri_target_marging", precision = 10)
	public BigDecimal getPriTargetMarging() {
		return this.priTargetMarging;
	}

	public void setPriTargetMarging(BigDecimal priTargetMarging) {
		this.priTargetMarging = priTargetMarging;
	}

	@Column(name = "pri_revenue", precision = 10)
	public BigDecimal getPriRevenue() {
		return this.priRevenue;
	}

	public void setPriRevenue(BigDecimal priRevenue) {
		this.priRevenue = priRevenue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pricing")
	public Set getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set proyectos) {
		this.proyectos = proyectos;
	}

}
