package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TimeReport generated by hbm2java
 */
@Entity
@Table(name = "time_report")
public class TimeReport implements java.io.Serializable {

	private int trpId;
	private Asignacion asignacion;
	private BigDecimal trpHoras;
	private BigDecimal trpTarifa;
	private Date trpFechaInicio;
	private Date trpFechaFin;
	private Long trpHorasTotales;

	public TimeReport() {
	}

	public TimeReport(int trpId, Asignacion asignacion, Date trpFechaInicio, Date trpFechaFin) {
		this.trpId = trpId;
		this.asignacion = asignacion;
		this.trpFechaInicio = trpFechaInicio;
		this.trpFechaFin = trpFechaFin;
	}

	public TimeReport(int trpId, Asignacion asignacion, BigDecimal trpHoras, BigDecimal trpTarifa, Date trpFechaInicio,
			Date trpFechaFin, Long trpHorasTotales) {
		this.trpId = trpId;
		this.asignacion = asignacion;
		this.trpHoras = trpHoras;
		this.trpTarifa = trpTarifa;
		this.trpFechaInicio = trpFechaInicio;
		this.trpFechaFin = trpFechaFin;
		this.trpHorasTotales = trpHorasTotales;
	}

	@Id

	@Column(name = "trp_id", unique = true, nullable = false)
	public int getTrpId() {
		return this.trpId;
	}

	public void setTrpId(int trpId) {
		this.trpId = trpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_asignacion", nullable = false)
	public Asignacion getAsignacion() {
		return this.asignacion;
	}

	public void setAsignacion(Asignacion asignacion) {
		this.asignacion = asignacion;
	}

	@Column(name = "trp_horas", precision = 10)
	public BigDecimal getTrpHoras() {
		return this.trpHoras;
	}

	public void setTrpHoras(BigDecimal trpHoras) {
		this.trpHoras = trpHoras;
	}

	@Column(name = "trp_tarifa", precision = 10)
	public BigDecimal getTrpTarifa() {
		return this.trpTarifa;
	}

	public void setTrpTarifa(BigDecimal trpTarifa) {
		this.trpTarifa = trpTarifa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "trp_fecha_inicio", nullable = false, length = 29)
	public Date getTrpFechaInicio() {
		return this.trpFechaInicio;
	}

	public void setTrpFechaInicio(Date trpFechaInicio) {
		this.trpFechaInicio = trpFechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "trp_fecha_fin", nullable = false, length = 29)
	public Date getTrpFechaFin() {
		return this.trpFechaFin;
	}

	public void setTrpFechaFin(Date trpFechaFin) {
		this.trpFechaFin = trpFechaFin;
	}

	@Column(name = "trp_horas_totales")
	public Long getTrpHorasTotales() {
		return this.trpHorasTotales;
	}

	public void setTrpHorasTotales(Long trpHorasTotales) {
		this.trpHorasTotales = trpHorasTotales;
	}

}
