package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPago generated by hbm2java
 */
@Entity
@Table(name = "tipo_pago")
public class TipoPago implements java.io.Serializable {

	private int tpgId;
	private String tpgNombre;
	private String tpgDescripcion;
	private Set metodoPagos = new HashSet(0);

	public TipoPago() {
	}

	public TipoPago(int tpgId) {
		this.tpgId = tpgId;
	}

	public TipoPago(int tpgId, String tpgNombre, String tpgDescripcion, Set metodoPagos) {
		this.tpgId = tpgId;
		this.tpgNombre = tpgNombre;
		this.tpgDescripcion = tpgDescripcion;
		this.metodoPagos = metodoPagos;
	}

	@Id

	@Column(name = "tpg_id", unique = true, nullable = false)
	public int getTpgId() {
		return this.tpgId;
	}

	public void setTpgId(int tpgId) {
		this.tpgId = tpgId;
	}

	@Column(name = "tpg_nombre")
	public String getTpgNombre() {
		return this.tpgNombre;
	}

	public void setTpgNombre(String tpgNombre) {
		this.tpgNombre = tpgNombre;
	}

	@Column(name = "tpg_descripcion")
	public String getTpgDescripcion() {
		return this.tpgDescripcion;
	}

	public void setTpgDescripcion(String tpgDescripcion) {
		this.tpgDescripcion = tpgDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPago")
	public Set getMetodoPagos() {
		return this.metodoPagos;
	}

	public void setMetodoPagos(Set metodoPagos) {
		this.metodoPagos = metodoPagos;
	}

}
